// Loaded only inside CloudCannon's Visual Editor (see BaseLayout.astro).
// Register only components whose data changes their rendered structure or styling.
// The shared header and footer use primitive external-data editables directly; wrapping
// either in a registered component creates a nested Dataset re-render race in 0.0.19.
import { registerAstroComponent } from '@cloudcannon/editable-regions/astro';
import EditableGlowCTA from './components/EditableGlowCTA.astro';
import EditableCaseStudyCTA from './components/EditableCaseStudyCTA.astro';
import EditablePricingPlans from './components/EditablePricingPlans.astro';
import EditableSeriesCTA from './components/EditableSeriesCTA.astro';
import EditableEditorialQuote from './components/EditableEditorialQuote.astro';
import EditableVoiceIntro from './components/EditableVoiceIntro.astro';
import EditableResearchCTA from './components/EditableResearchCTA.astro';
import EditableBringItCTA from './components/EditableBringItCTA.astro';
import EditableEditorialCTA from './components/EditableEditorialCTA.astro';
import EditableSplitCTA from './components/EditableSplitCTA.astro';
import EditableAboutTimeline from './components/EditableAboutTimeline.astro';
import EditableAboutVoices from './components/EditableAboutVoices.astro';
import EditableAboutTeam from './components/EditableAboutTeam.astro';
import EditableFAQPricing from './components/EditableFAQPricing.astro';
import EditableFAQQuotes from './components/EditableFAQQuotes.astro';
import EditableDistrictHero from './components/EditableDistrictHero.astro';
import EditableDistrictNumbers from './components/EditableDistrictNumbers.astro';
import EditableDistrictDay from './components/EditableDistrictDay.astro';
import EditableDistrictComparison from './components/EditableDistrictComparison.astro';
import EditableHomeLiveNow from './components/EditableHomeLiveNow.astro';
import EditableHomeHowItWorks from './components/EditableHomeHowItWorks.astro';
import EditableHomeProof from './components/EditableHomeProof.astro';
import EditableHomeStories from './components/EditableHomeStories.astro';
import EditablePlatformFeature from './components/EditablePlatformFeature.astro';
import EditablePlatformUpdates from './components/EditablePlatformUpdates.astro';
import EditablePlatformImpact from './components/EditablePlatformImpact.astro';
import EditablePlatformOutcomes from './components/EditablePlatformOutcomes.astro';
import EditableResearchHero from './components/EditableResearchHero.astro';
import EditableListingMasthead from './components/EditableListingMasthead.astro';
import EditableContactMasthead from './components/EditableContactMasthead.astro';
import EditablePricingMasthead from './components/EditablePricingMasthead.astro';
import EditableFAQMasthead from './components/EditableFAQMasthead.astro';
import EditableMeetStudioHero from './components/EditableMeetStudioHero.astro';
import FAQSection from '../components/blocks/FAQSection.astro';

registerAstroComponent('glow-cta', EditableGlowCTA);
registerAstroComponent('case-study-cta', EditableCaseStudyCTA);
registerAstroComponent('pricing-plans', EditablePricingPlans);
registerAstroComponent('series-cta', EditableSeriesCTA);
registerAstroComponent('editorial-quote', EditableEditorialQuote);
registerAstroComponent('voice-intro', EditableVoiceIntro);
registerAstroComponent('research-cta', EditableResearchCTA);
registerAstroComponent('bring-it-cta', EditableBringItCTA);
registerAstroComponent('editorial-cta', EditableEditorialCTA);
registerAstroComponent('split-cta', EditableSplitCTA);
registerAstroComponent('faq-section', FAQSection);
registerAstroComponent('about-timeline', EditableAboutTimeline);
registerAstroComponent('about-voices', EditableAboutVoices);
registerAstroComponent('about-team', EditableAboutTeam);
registerAstroComponent('faq-pricing', EditableFAQPricing);
registerAstroComponent('faq-quotes', EditableFAQQuotes);
registerAstroComponent('district-hero', EditableDistrictHero);
registerAstroComponent('district-numbers', EditableDistrictNumbers);
registerAstroComponent('district-day', EditableDistrictDay);
registerAstroComponent('district-comparison', EditableDistrictComparison);
registerAstroComponent('home-live-now', EditableHomeLiveNow);
registerAstroComponent('home-how-it-works', EditableHomeHowItWorks);
registerAstroComponent('home-proof', EditableHomeProof);
registerAstroComponent('home-stories', EditableHomeStories);
registerAstroComponent('platform-feature', EditablePlatformFeature);
registerAstroComponent('platform-updates', EditablePlatformUpdates);
registerAstroComponent('platform-impact', EditablePlatformImpact);
registerAstroComponent('platform-outcomes', EditablePlatformOutcomes);
registerAstroComponent('research-hero', EditableResearchHero);
registerAstroComponent('listing-masthead', EditableListingMasthead);
registerAstroComponent('contact-masthead', EditableContactMasthead);
registerAstroComponent('pricing-masthead', EditablePricingMasthead);
registerAstroComponent('faq-masthead', EditableFAQMasthead);
registerAstroComponent('meet-studio-hero', EditableMeetStudioHero);
